---
# tasks file for win_ad_user

- name: creating users
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{item.firstname }}"
    lastname: "{{ item.lastname }}"
    password: "{{ item.password }}"
    email: '"{{ item.email }}"'
    state: present
  with_items: "{{ dict }}"
