---
# tasks file for win_service_config

- name: Install packages
  win_chocolatey:
    name: '{{ item }}'
    params: "{{ parameters }}"
    state: present
  with_items:
  - "{{ package_name }}"
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'

- name: Start service
  win_service:
    name: "{{ service_name }}"
    state: restarted
  when: ansible_distribution == 'Microsoft Windows Server 2012 R2 Standard'

- name: add service in firewall
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: 22
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

